import Head from "next/head";
import Navbar from "./components/Navbar";
import Features from "./components/Features"; 
import { Select } from '@chakra-ui/react'
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>YUUP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
          <Navbar />
        <div className="Hero">
          <h1 className="">
            Welcome to the{" "}
            <span className="text-orange">only Resource Website</span> for{" "}
            <span className="underline"> 
            EN
            </span>
          </h1>
          <button className="btn"> <Link href={'./components/Login'}> Login To Site </Link> </button>
        </div> 
        <div className="res">
          <Features  />
        </div>
      </main>
    </>
  );
}
